[package]
name = "cabi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]
# crate-type = ["cdylib"] dynamic linking

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version = "1.23", features = ["full"]}
